# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/design_2_axi_smc_2.xci
# IP: The module: 'design_2_axi_smc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/bd_2a4d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_0/bd_2a4d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_1/bd_2a4d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_2/bd_2a4d_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_3/bd_2a4d_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_4/bd_2a4d_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_5/bd_2a4d_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_6/bd_2a4d_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_7/bd_2a4d_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_8/bd_2a4d_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_9/bd_2a4d_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_10/bd_2a4d_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_11/bd_2a4d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_12/bd_2a4d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_13/bd_2a4d_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_14/bd_2a4d_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_15/bd_2a4d_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_16/bd_2a4d_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_17/bd_2a4d_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_18/bd_2a4d_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_19/bd_2a4d_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_20/bd_2a4d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_21/bd_2a4d_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_22/bd_2a4d_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_23/bd_2a4d_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_24/bd_2a4d_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_25/bd_2a4d_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_26/bd_2a4d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_1/bd_2a4d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_1/bd_2a4d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_2/bd_2a4d_arsw_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_3/bd_2a4d_rsw_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_4/bd_2a4d_awsw_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_5/bd_2a4d_wsw_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_6/bd_2a4d_bsw_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_10/bd_2a4d_s00a2s_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_11/bd_2a4d_sarn_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_12/bd_2a4d_srn_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_16/bd_2a4d_s01a2s_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_17/bd_2a4d_sawn_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_18/bd_2a4d_swn_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_19/bd_2a4d_sbn_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_20/bd_2a4d_m00s2a_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_21/bd_2a4d_m00arn_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_22/bd_2a4d_m00rn_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_23/bd_2a4d_m00awn_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_24/bd_2a4d_m00wn_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_25/bd_2a4d_m00bn_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axi_smc_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/design_2_axi_smc_2.xci
# IP: The module: 'design_2_axi_smc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/bd_2a4d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_0/bd_2a4d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_1/bd_2a4d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_2/bd_2a4d_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_3/bd_2a4d_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_4/bd_2a4d_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_5/bd_2a4d_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_6/bd_2a4d_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_7/bd_2a4d_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_8/bd_2a4d_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_9/bd_2a4d_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_10/bd_2a4d_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_11/bd_2a4d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_12/bd_2a4d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_13/bd_2a4d_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_14/bd_2a4d_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_15/bd_2a4d_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_16/bd_2a4d_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_17/bd_2a4d_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_18/bd_2a4d_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_19/bd_2a4d_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_20/bd_2a4d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_21/bd_2a4d_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_22/bd_2a4d_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_23/bd_2a4d_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_24/bd_2a4d_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_25/bd_2a4d_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_26/bd_2a4d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_1/bd_2a4d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_1/bd_2a4d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_2/bd_2a4d_arsw_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_3/bd_2a4d_rsw_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_4/bd_2a4d_awsw_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_5/bd_2a4d_wsw_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_6/bd_2a4d_bsw_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_10/bd_2a4d_s00a2s_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_11/bd_2a4d_sarn_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_12/bd_2a4d_srn_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_16/bd_2a4d_s01a2s_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_17/bd_2a4d_sawn_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_18/bd_2a4d_swn_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_19/bd_2a4d_sbn_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_20/bd_2a4d_m00s2a_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_21/bd_2a4d_m00arn_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_22/bd_2a4d_m00rn_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_23/bd_2a4d_m00awn_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_24/bd_2a4d_m00wn_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/bd_0/ip/ip_25/bd_2a4d_m00bn_0_ooc.xdc

# XDC: c:/Projects/Accelerator/near-memory-radix-sort/Hardware/near_memory_radix_sort/near_memory_radix_sort.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axi_smc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
