@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Jun 23 13:15:38 +0900 2021
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_radix_sort_accelerator_v1_0_behav -key {Behavioral:sim_1:Functional:tb_radix_sort_accelerator_v1_0} -tclbatch tb_radix_sort_accelerator_v1_0.tcl -view C:/Projects/Accelerator/near-memory-radix-sort/Hardware/radix_sort_simulator/tb_radix_sort_accelerator_v1_0_behav.wcfg -view C:/Projects/Accelerator/near-memory-radix-sort/Hardware/radix_sort_simulator/tb_data_shifter_behav.wcfg -view C:/Projects/Accelerator/near-memory-radix-sort/Hardware/radix_sort_simulator/tb_first_behav.wcfg -view C:/Projects/Accelerator/near-memory-radix-sort/Hardware/radix_sort_simulator/tb_two_bram_radix_sorter_behav.wcfg -view C:/Projects/Accelerator/near-memory-radix-sort/Hardware/radix_sort_simulator/tb_radix_sorting_unit_behav.wcfg -log simulate.log"
call xsim  tb_radix_sort_accelerator_v1_0_behav -key {Behavioral:sim_1:Functional:tb_radix_sort_accelerator_v1_0} -tclbatch tb_radix_sort_accelerator_v1_0.tcl -view C:/Projects/Accelerator/near-memory-radix-sort/Hardware/radix_sort_simulator/tb_radix_sort_accelerator_v1_0_behav.wcfg -view C:/Projects/Accelerator/near-memory-radix-sort/Hardware/radix_sort_simulator/tb_data_shifter_behav.wcfg -view C:/Projects/Accelerator/near-memory-radix-sort/Hardware/radix_sort_simulator/tb_first_behav.wcfg -view C:/Projects/Accelerator/near-memory-radix-sort/Hardware/radix_sort_simulator/tb_two_bram_radix_sorter_behav.wcfg -view C:/Projects/Accelerator/near-memory-radix-sort/Hardware/radix_sort_simulator/tb_radix_sorting_unit_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
